### ISSUE TITLE
Error: Failed to load the pb-completions package

### ISSUE THREAD

**Issue by tilden** [jneubrand/pb-completions#1]
I'm getting this error every time I start Atom -- it appears that the package isn't loading?

Steps to reproduce:
1. Install package
2. Run Atom

**Atom Version**: 1.5.1
**System**: Mac OS X 10.11.2
**Thrown From**: [pb-completions](https://github.com/jneubrand/pb-completions) package, v1.0.18

### Stack Trace

Failed to load the pb-completions package

```
At Unexpected end of input

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.reloadHeaders (/Users/Dan/.atom/packages/pb-completions/lib/provider.js:354:34)
    at Object.reload (/Users/Dan/.atom/packages/pb-completions/lib/provider.js:415:28)
    at Object.maybeReload (/Users/Dan/.atom/packages/pb-completions/lib/provider.js:458:28)
    at reinitProvider (/Users/Dan/.atom/packages/pb-completions/lib/pb-completions.js:112:14)
    at Object.<anonymous> (/Users/Dan/.atom/packages/pb-completions/lib/pb-completions.js:117:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
pb-completions, v1.0.18
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by bwinton** [comment]
It looks like this is caused by `localStorage.PbCompletionsStoredItem_Symbols` having a value of "".  I'm not sure why that's the case, but judicious use of `|| "[]"` at line 352 of provider.js would help.  :wink:

**Comment by jneubrand** [comment]
@bwinton: Actually, the fix is changing `[]` to `JSON.stringify([])` at https://github.com/jneubrand/pb-completions/blob/master/lib/provider.js#L23 :)

**Comment by jneubrand** [comment]
LMK if you experience any problems after this update :)

**Comment by tilden** [comment]
Works great now! Thanks!

**Comment by jneubrand** [comment]
Great :)
